#!/bin/bash

cargo build --release --target x86_64-pc-windows-gnu
mkdir -p ./windows_export
cp ./target/x86_64-pc-windows-gnu/release/*.exe ./windows_export/kanalis.exe
7z a windows_export.7z ./windows_export
